fix: Move branch name from master to main
logdna/logger-node pull request #43
Opened 2021-02-08 21:16 UTC by darinspivey

2021-02-08 21:31 UTC, smusali approved these changes

2021-02-08 22:25 UTC, mdeltito approved these changes

2021-02-08 22:26 UTC, mdeltito requested changes
ah, `CONTRIBUTING.md` and `README.md` need an update as well

2021-02-09 00:06 UTC, darinspivey commented
> ah, `CONTRIBUTING.md` and `README.md` need an update as well

They do, how? They were  just updated the other day.

2021-02-09 00:30 UTC, mdeltito commented
> > ah, `CONTRIBUTING.md` and `README.md` need an update as well
> 
> They do, how? They were just updated the other day.

They both reference `master` in the contents. The README just needs the badge url updated.

2021-02-09 14:28 UTC, jorgebay approved these changes

2021-02-09 15:22 UTC, mdeltito approved these changes

2021-02-09 15:22 UTC, merged